
# Numpy array. Практическая работа

## Цель практической работы

Выполните задачи, чтобы потренироваться в использовании функционала NumPy.

## Что входит в практическое задание

10 задач на использование библиотеки NumPy.


## Что нужно сделать

Скачайте файл с заданием в материалах, откройте его через Jupyter Notebook и выполните задачи. Сверьтесь с ответами, представленными ниже. Обратите внимание, что это задание не нужно сдавать на проверку.


## Задачи


1. Создайте вектор размера 10, заполненный нулями, но пятый элемент которого равен 1.

In [ ]:
# ваш код здесь

2. Создайте вектор со значениями от 10 до 49.

In [ ]:
# ваш код здесь

3. Создайте матрицу (двумерный массив) 3x3 со значениями от 0 до 8.

In [ ]:
# ваш код здесь

4. Создайте массив 3x3x3 со случайными значениями.

In [ ]:
# ваш код здесь

5. Создайте матрицу 10x10 с 0 внутри и 1 на границах.

In [ ]:
# ваш код здесь

6. Создайте матрицы  5x3 и 3x2 со случайными значениями и перемножьте их.

In [ ]:
# ваш код здесь

Для выполнения задач 7–10 создайте массив 10x10 со значениями от 1 до 100 и все вычисления производите на нём.



7. Замените максимальный элемент матрицы на ноль.

In [ ]:
# ваш код здесь

8. Отнимите среднее из каждой строки в матрице.

In [ ]:
# ваш код здесь

9. Посчитайте сумму по последним двум осям.

In [ ]:
# ваш код здесь

10. Поменяйте две строки в матрице.

In [ ]:
# ваш код здесь

|

|

|

|

|

|

|

|

|

|

|

## Решения

In [ ]:
import numpy as np

1. Создать вектор размера 10, заполненный нулями, но пятый элемент которого равен 1.

In [ ]:
A = np.zeros(10)
A[5] = 1
A

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

2. Создать вектор со значениями от 10 до 49.

In [ ]:
A = np.arange(10, 50)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8.

In [ ]:
A = np.arange(9)
A = np.reshape(A, (3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Создать массив 3x3x3 со случайными значениями.

In [ ]:
A = np.random.randn(27)
A = np.reshape(A, (3,3,3)) # не бойтесь брать размерность больше - сам функционал не меняется
A

array([[[-0.41336332,  0.24282681, -0.42799157],
        [ 2.19514652, -0.08845199, -0.26187101],
        [ 0.65486936,  1.58429859,  0.61049483]],

       [[ 3.31091876,  0.31353579, -1.03678795],
        [-0.03668153,  0.94854215, -0.34772407],
        [-0.64978004, -0.04614266, -0.6312112 ]],

       [[ 1.7907814 ,  0.04389523, -1.46941623],
        [ 0.03594945, -0.62600865,  2.43020817],
        [ 0.44822002,  1.57768507,  3.36214885]]])

5. Создать матрицу 10x10 с 0 внутри и 1 на границах.

In [ ]:
A = np.ones([10,10])
A [1:-1, 1:-1] = 0
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

6. Создать матрицы  5x3 и 3x2 со случайными значениями и перемножить их.

In [ ]:
A = np.random.randn(15)
A = np.reshape(A, (5,3))
A

array([[-0.01722222, -1.41473573, -0.20005992],
       [ 0.42191763, -0.04913356,  0.45401592],
       [-0.18640826, -0.75528913, -1.0106215 ],
       [ 0.68122794,  0.28916362,  1.21614174],
       [ 0.32067439, -0.29316138,  1.45262855]])

In [ ]:
B = np.random.randn(6)
B = np.reshape(B, (3,2))
B

array([[ 1.08424121,  0.31301797],
       [-0.24584297, -0.66979163],
       [ 0.26456723,  0.15239299]])

В задании не сказано, как перемножать матрицы: поэлементно или согласно правилам матричного перемножения. Так как поэлементное умножение вызовет ошибку, потому что размерности матриц не согласуются, выполним матричное перемножение:

In [ ]:
np.dot(A, B)

array([[ 0.2762005 ,  0.91169955],
       [ 0.58965736,  0.23416589],
       [-0.28380633,  0.29352557],
       [ 0.98927781,  0.20488868],
       [ 0.80407797,  0.51810428]])

|

Создать массив 10x10 со значениями от 1 до 100.

In [ ]:
A = np.arange(1,101)
A = np.reshape(A, (10,10))
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

7. Заменить максимальный элемент матрицы на ноль.

In [ ]:
A[A == A.max()] = 0
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99,  0]])

8. Отнять среднее из каждой строки в матрице.

In [ ]:
A - A.mean()

array([[-48.5, -47.5, -46.5, -45.5, -44.5, -43.5, -42.5, -41.5, -40.5,
        -39.5],
       [-38.5, -37.5, -36.5, -35.5, -34.5, -33.5, -32.5, -31.5, -30.5,
        -29.5],
       [-28.5, -27.5, -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5,
        -19.5],
       [-18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,
         -9.5],
       [ -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,  -1.5,  -0.5,
          0.5],
       [  1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,   9.5,
         10.5],
       [ 11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,  18.5,  19.5,
         20.5],
       [ 21.5,  22.5,  23.5,  24.5,  25.5,  26.5,  27.5,  28.5,  29.5,
         30.5],
       [ 31.5,  32.5,  33.5,  34.5,  35.5,  36.5,  37.5,  38.5,  39.5,
         40.5],
       [ 41.5,  42.5,  43.5,  44.5,  45.5,  46.5,  47.5,  48.5,  49.5,
        -49.5]])

9. Посчитать сумму по последним двум строкам.

In [ ]:
A[-2:].sum(axis=1)

array([855, 855])

10. Поменять две строки в матрице.

Поменяем первую и последнюю строки:

In [ ]:
A[[0,9]] = A[[9,0]]
A

array([[91, 92, 93, 94, 95, 96, 97, 98, 99,  0],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])